### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by kaushalvivek** [Gregwar/notroot#6]
Error Report:
```bash
otroot install vim
[NOTROOT] Installing vim from yum...
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
Traceback (most recent call last):
  File "/bin/yumdownloader", line 283, in <module>
    util = YumDownloader()
  File "/bin/yumdownloader", line 79, in __init__
    self.main()
  File "/bin/yumdownloader", line 108, in main
    self.doUtilYumSetup(opts)
  File "/bin/yumdownloader", line 249, in doUtilYumSetup
    self._getRepos(doSetup = True)
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 721, in _getRepos
    self._repos.doSetup(thisrepo)
  File "/usr/lib/python2.7/site-packages/yum/repos.py", line 122, in doSetup
    self.ayum.plugins.run('prereposetup')
  File "/usr/lib/python2.7/site-packages/yum/plugins.py", line 188, in run
    func(conduitcls(self, self.base, conf, **kwargs))
  File "/usr/lib/yum-plugins/fastestmirror.py", line 202, in prereposetup_hook
    all_urls = FastestMirror(all_urls).get_mirrorlist()
  File "/usr/lib/yum-plugins/fastestmirror.py", line 369, in get_mirrorlist
    self._poll_mirrors()
  File "/usr/lib/yum-plugins/fastestmirror.py", line 413, in _poll_mirrors
    pollThread.start()
  File "/usr/lib64/python2.7/threading.py", line 747, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
```

**Comment by Gregwar** [comment]
https://stackoverflow.com/a/1835043

Looks like this is related to restriction on your system itself
I am not sure how to debug that (`yum` process is reaching maximum amount of threads)

**Comment by kaushalvivek** [comment]
Thanks for the quick response @Gregwar , I'll keep you posted.
